version: '2'
services:
  catalogue-app:
    image: catalogue
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://catalogue-mysql:3306/catalogue?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://catalogue-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://catalogue-elasticsearch:9200
  catalogue-mysql:
    extends:
      file: mysql.yml
      service: catalogue-mysql
  catalogue-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catalogue-elasticsearch
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
